# NAME: Emotn
# AUTHOR: blackmatrix7
# REPO: https://github.com/blackmatrix7/ios_rule_script
# UPDATED: 2025-06-06 09:16:55
# DOMAIN-KEYWORD: 1
# DOMAIN-SUFFIX: 6
# IP-CIDR: 0
# TOTAL: 6
DOMAIN-SUFFIX,app.emotn.com
DOMAIN-SUFFIX,update.emotn.com
DOMAIN-SUFFIX,api.emotn.com
DOMAIN-SUFFIX,cdn.emotn.com
DOMAIN-SUFFIX,res.emotn.com
DOMAIN-SUFFIX,share.emotn.com
